version: "3.9"
services:
    gp-rest-api-builder:
        container_name: gp-rest-api-builder
        volumes:
            - gp-rest-api-builder:/gp-rest-api
            - gp-migration-builder:/gp-migration
        build:
            context: ./rest-api
            dockerfile: Dockerfile
            args:
                DefaultConnection: server=gp-mssql;user id=SA;password=Password123!;database=GP

    gp-web-client-builder:
        container_name: gp-web-client-builder
        depends_on:
            - gp-rest-api-builder
        volumes:
            - gp-web-client-builder:/gp-web-client
        build:
            context: ./web-client
            dockerfile: Dockerfile
            args:
                RestApiUrl: http://localhost:5000/api

    gp-mssql:
        container_name: gp-mssql
        image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-18.04
        depends_on:
            - gp-rest-api-builder
            - gp-web-client-builder
        volumes:
            - gp-mssql-data:/var/opt/mssql
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: Password123!
            ACCEPT_EULA: Y

    gp-migration:
        container_name: gp-migration
        image: mcr.microsoft.com/dotnet/aspnet:5.0
        depends_on:
            - gp-mssql
        volumes:
            - gp-migration-builder:/gp-migration
        working_dir: /gp-migration
        entrypoint: ./GreatPizza.Infrastructure.Migration

    gp-rest-api:
        container_name: gp-rest-api
        image: mcr.microsoft.com/dotnet/aspnet:5.0
        depends_on:
            - gp-migration
        volumes:
            - gp-rest-api-builder:/gp-rest-api
        ports:
            - 5000:80
        working_dir: /gp-rest-api
        entrypoint: ./GreatPizza.WebApi

    gp-web-client:
        container_name: gp-web-client
        image: nginx:1.21-alpine
        depends_on:
            - gp-rest-api
        volumes:
            - ./web-client/default.conf:/etc/nginx/conf.d/default.conf
            - gp-web-client-builder:/usr/share/nginx/html
        ports:
            - 4200:80

volumes:
    gp-mssql-data:
    gp-rest-api-builder:
    gp-migration-builder:
    gp-web-client-builder:
